# Proxy Register  from channel

POST http://localhost:9002/komi-outbound/service HTTP/1.1
Content-Type: application/json
Authorization: Basic CMS:password

{
    "ProxyRegistrationRequest" : {
        "NoRef" : "FRN8544{{$randomInt 1000 9999}}",
        "RegistrationType" : "PORT",
        "ProxyType" : "01",
        "ProxyValue" : "0811133444",
        "AccountNumber" : "225224",
        "AccountType" : "CACC",
        "SecondaryIdType" : "01",
        "SecondaryIdValue" : "1020304050607080"
    }
}

###
POST http://localhost:9002/komi-outbound/service HTTP/1.1
Content-Type: application/json
Authorization: Basic CMS:password

{
    "ProxyRegistrationRequest": {
        "NoRef": "15562202",
        "RegistrationType": "AMND",
        "ProxyType" : "02",
        "ProxyValue" : "frans.mazhar@gmail.com",
        "DisplayName" : "Frans Mazhar",
        "AccountName" : "Fras Manse",
        "SecondaryIdType" : "01",
        "SecondaryIdValue" : "44443333",
        "CustomerType" : "01",
        "CustomerId" : "2200111022",
        "ResidentialStatus" : "01",
        "TownName" : "0300"
    }
}

###

POST http://localhost:9002/komi-outbound/service HTTP/1.1
Content-Type: application/json
Authorization: Basic CMS:password

{
    "ProxyRegistrationRequest" : {
        "NoRef" : "1511652",
        "RegistrationType" : "NEWR",
        "ProxyType" : "02",
        "ProxyValue" : "bams@gmail.com",
        "DisplayName" : "JOHN SMITH",
        "AccountNumber" : "2040606090112 ",
        "AccountType" : "CACC",
        "AccountName" : "JOHN SMITH ",
        "SecondaryIdType" : "01",
        "SecondaryIdValue" : "KTP-222044020",
        "CustomerType" : "01",
        "CustomerId" : "KTP-222044020",
        "ResidentialStatus" : "01",
        "TownName" : "0300"
    }
}