# Proxy Resolution  from channel
POST http://localhost:9002/komi-outbound/service HTTP/1.1
Content-Type: application/json
Authorization: Basic CMS:password

{
    "ProxyResolutionRequest": {
        "NoRef": "15216747",
        "SenderAccountNumber" : "223411112",
        "ProxyType" : "01",
        "ProxyValue" : "08111555666"
    }
}

###

POST http://localhost:9002/komi-outbound/service HTTP/1.1
Content-Type: application/json
Authorization: Basic CMS:password

{
    "ProxyResolutionRequest": {
        "NoRef": "1275",
        "SenderAccountNumber" : "22341111",
        "ProxyType" : "02",
        "ProxyValue" : "yogi@gmail.com"
    }
}
