# Proxy Resolution  from channel
POST http://localhost:9002/komi-outbound/service HTTP/1.1
Content-Type: application/json
Authorization: Basic CMS:password

{
    "ProxyResolutionRequest": {
        "NoRef": "5462",
        "SenderAccountNumber" : "22341111",
        "ProxyType" : "02",
        "ProxyValue" : "yogi@gmail.com"
    }
}
