POST http://localhost:9003/komi/api/v1/adapter HTTP/1.1
Content-Type: application/json

{
  "AccountEnquiryRequest" : {
    "komiTrnsId" : "47169",
    "categoryPurpose" : "01",
    "accountNumber" : "7723004444",
    "amount" : "137400"
  }
}

###
