INSERT INTO mock_names VALUES 
('Anton'),
('Andrea'),
('Windi'),
('Jhony'),
('Wirawan'),
('Aditya'),
('Suseno'),
('Susilo'),
('Ambarwati'),
('Eko'),
('Adiputro'),
('Johan'),
('Adam'),
('Bustami'),
('Joko'),
('Indarto'),
('Kusuma'),
('Yogi'),
('Gilang'),
('Samudera'),
('Andre'),
('Sjafril'),
('Widodo'),
('Syamsul'),
('Erwin'),
('Reni'),
('Winata'),
('Hadi'),
('Yudistira');

insert into ACCOUNT_PROXY (ID,ACCOUNT_NAME,ACCOUNT_NUMBER,ACCOUNT_STATUS,ACCOUNT_TYPE,DISPLAY_NAME,PROXY_TYPE,PROXY_VAL,REGISTER_BANK,SCND_ID_TP,SCND_ID_VAL) values 
('1','Andrian S','112211333','ACTV','CACC','Andrian S','01','2233002','INDOIDJA','01','12345678'),
('2','Yogi Lestari','12134863112','ACTV','CACC','Yogi Lestari','02','yogi@gmail.com','INDOIDJA','01','1020304050607080');
