# Account Enquiry Request from channel on generic endpoint
# Account Number 77xxxx TIMEOUT

POST http://localhost:9002/komi-outbound/service HTTP/1.1
Content-Type: application/json
Authorization: Basic CMS:password

{
  "AccountEnquiryRequest" : {
    "NoRef" : "36457",
    "SenderAccountNumber": "5230",
    "RecipientBank" : "CITYIDJA",
    "Amount" : "24520064.00",
    "CategoryPurpose" : "01",
    "RecipientAccountNumber" : "2561839"
 }
}

###
#  dengan proxy
POST http://localhost:9002/komi-outbound/service HTTP/1.1
Content-Type: application/json
Authorization: Basic CMS:password

{
  "AccountEnquiryRequest" : {
    "NoRef" : "5535",
    "SenderAccountNumber": "54130",
    "Amount" : "245000",
    "CategoryPurpose" : "01",
    "ProxyType" : "01",
    "ProxyId" : "2233002"
 }
}

###
    "RecipientAccountNumber" : "464589"
    "ProxyType" : "012",
    "ProxyId" : "20033002"

