# Account Enquiry Request from channel on generic endpoint
# Account Number 77xxxx TIMEOUT

POST http://localhost:9002/komi-outbound/service HTTP/1.1
Content-Type: application/json
Authorization: Basic CMS:password

{
  "AccountEnquiryRequest" : {
    "NoRef" : "36655438",
    "SenderAccountNumber": "14395230",
    "RecipientBank" : "CITYIDJA",
    "Amount" : "24520064.00",
    "CategoryPurpose" : "01",
    "RecipientAccountNumber" : "3175771839",
    "ProxyType" : "01",
    "ProxyId" : "22330021"
 }
}

###
#  dengan proxy
POST http://localhost:9002/komi-outbound/service HTTP/1.1
Content-Type: application/json
Authorization: Basic CMS:password

{
  "AccountEnquiryRequest" : {
    "NoRef" : "5557367",
    "SenderAccountNumber": "54130",
    "Amount" : "245000.00",
    "CategoryPurpose" : "01",
    "ProxyType" : "01",
    "ProxyId" : "22330021"
 }
}

###
    "RecipientAccountNumber" : "464589"
    "ProxyType" : "012",
    "ProxyId" : "20033002"

