# accountNumber '9***' akan reject K000
POST http://localhost:9002/komi-outbound/service HTTP/1.1
Content-Type: application/json
Authorization: Basic MB:mb2022

{
  "AccountCustomerInfo" : {
    "NoRef" : "MOB22010808234{{$randomInt 1000 9999}}", 
    "TerminalId" : "MOBILE0001",  
    "AccountNumber" : "3602103332331"
  }
}

###
POST http://10.11.103.65:9002/komi-outbound/service HTTP/1.1
Content-Type: application/json
Authorization: Basic MB:mb2022

{
  "AccountCustomerInfo" : {
    "NoRef" : "MOB22010808234{{$randomInt 1000 9999}}", 
    "TerminalId" : "MOBILE0001",  
    "AccountNumber" : "3602103332330"
  }
}