
POST http://localhost:9002/komi-outbound/service HTTP/1.1
Content-Type: application/json
Authorization: Basic CMS:password

{
  "AccountCustomerInfo" : {
    "NoRef" : "202652", 
    "TerminalId" : "T00000",  
    "AccountNumber" : "2012104794259"
  }
}