# Credit Transfer Request from channel on generic endpoint

# "PaymentInformation": "CB-RJCT" -->.. akan reject by CB
# norekCreditor 5xx akan response reject
# jika norekCreditor 221211999 RJCT 
# Jika payInfo TIMEOUT, akan Timeout
# jika norekCreditor 99x reject admi002
# positif test refId bukan 9 dan norek bukan 77-8-9

#localhost:9002/komi-outbound/routing/
#localhost:9002/komi-outbound/service/

POST http://localhost:9002/komi-outbound/service HTTP/1.1
Content-Type: application/json
Authorization: Basic MB:password

{
	"CreditTransferRequest": {
		"NoRef": "FRN2201152{{$randomInt 1000 9999}}",
		"TerminalId": "MOBILE0001",
		"CategoryPurpose": "01",
		"CreditorAccountNumber": "112211333",
		"CreditorAccountType": "CACC",
		"CreditorId": "018029520054000",
		"CreditorType": "02",
		"CreditorName": "REKENING DANA INVESTASI NOSTRO",
		"CreditorResidentialStatus": "01",
		"CreditorTownName": "0300",
		"Amount": "60500.24",
		"FeeTransfer": "0.00",
		"RecipientBank": "CENAIDJA",
		"DebtorAccountNumber": "0002107551117",
		"DebtorAccountType": "SVGS",
		"DebtorId": "5171026206690001",
		"DebtorResidentialStatus": "01",
		"DebtorType": "01",
		"DebtorTownName": "0191",
		"DebtorName": "MURYATI",
		"PaymentInformation": ""
	}
}

###

POST http://localhost:9002/komi-outbound/service HTTP/1.1
Content-Type: application/json
Authorization: Basic MB:password

{
  "CreditTransferRequest": {
    "RecipientBank": "BMRIIDJA",
    "CategoryPurpose": "02",
    "FeeTransfer": "2500.00",
    "DebtorId": "5171020812700001",
    "Amount": "100000.00",
    "CreditorProxyType": "",
    "CreditorName": "I MADE SUTAMA",
    "CreditorAccountNumber": "1450004483893",
    "CreditorAccountType": "SVGS",
    "NoRef": "MOB220215104311720",
    "DebtorAccountType": "SVGS",
    "DebtorAccountNumber": "0012104678316",
    "DebtorResidentialStatus": "01",
    "DebtorType": "01",
    "CreditorProxyId": "",
    "PaymentInformation": "",
    "TerminalId": "MOBILE0001",
    "DebtorTownName": "7291",
    "DebtorName": "I MADE SUTAMA QQ SUKERTI"
  }
}

###
POST http://localhost:9002/komi-outbound/service HTTP/1.1
Content-Type: application/json
Authorization: Basic CB:password

{"CreditTransferRequest":{"NoRef":"MF280122120{{$randomInt 100 999}}","TerminalId":"QA0002","CategoryPurpose":"99","DebtorName":"DEWI SUHARTINI","DebtorType":"01","DebtorId":"3174016005650012","DebtorAccountNumber":"2012107552327","DebtorAccountType":"SVGS","DebtorResidentialStatus":"01","DebtorTownName":"0394","Amount":"25000.00","FeeTransfer":"2500.00","RecipientBank":"ROYBIDJ1","CreditorName":"","CreditorType":"01","CreditorId":"","CreditorAccountNumber":"000000000464","CreditorAccountType":"CACC","CreditorResidentialStatus":"01","CreditorTownName":"0191","CreditorProxyId":"RAV123@BCAD.COM","CreditorProxyType":"02","PaymentInformation":"TEST BIFAST"}}

###


###
POST http://localhost:9006/mock/adapter/debitreversal HTTP/1.1
Content-Type: application/json

{"transactionId":"000001","noRef":"FRN22011523278","merchantType":"5002","terminalId":"MOBILE0001","dateTime":"2022-02-02T21:26:22.440","originalNoRef":"FRN22011523278","originalDateTime":"2022-02-02T21:26:22.440","categoryPurpose":"01","debtorName":"MURYATI","debtorType":"01","debtorId":"5171026206690001","debtorAccountNumber":"0002107551117","debtorAccountType":"SVGS","debtorResidentStatus":"01","debtorTownName":"0191","amount":"60500.24","feeTransfer":"0.00","recipientBank":"KSEIIDJ1","creditorName":"REKENING DANA INVESTASI NOSTRO","creditorType":"02","creditorId":"018029520054000","creditorAccountNumber":"KSEI1PLC100156","creditorAccountType":"SVGS","creditorResidentStatus":"01","creditorTownName":"0300","paymentInformation":"Test mantap "}