# Payment Status Request from channel on generic endpoint
POST http://localhost:9002/komi-outbound/service HTTP/1.1
Content-Type: application/json
clientId: TELLER

{
    "PaymentStatusRequest" : {
      "NoRef" : "1112",
      "OriginalNoRef" : "1143"
    }
}

###
POST http://localhost:9006/mock/cihub HTTP/1.1
Content-Type: application/json

{
  "BusMsg": {
    "AppHdr": {
      "Fr": {
        "Fiid": {
          "FinInstnId": {
            "Othr": {
              "Id": "MNDRIDJA"
            }
          }
        }
      },
      "To": {
        "Fiid": {
          "FinInstnId": {
            "Othr": {
              "Id": "INDOIDJA"
            }
          }
        }
      },
      "BizMsgIdr": "20210912MNDRIDJA000O9900000101",
      "MsgDefIdr": "pacs.028.001.04",
      "CreDt": "2021-09-12T21:17:27"
    },
    "Document": {
      "FitoFIPmtStsReq": {
        "GrpHdr": {
          "MsgId": "20210912MNDRIDJA00000000102",
          "CreDtTm": 1631456247604
        },
        "TxInf": [
          {
            "OrgnlEndToEndId": "20210912MNDRIDJA010O0100000099"
          }
        ]
      }
    }
  }
}