# Proxy Register  from channel
POST http://localhost:9002/services/channel/proxyregistration HTTP/1.1
Content-Type: application/json

{
    "channel" : "01",
    "proxyTp" : "02",
    "proxyVal" : "frans.mazhar@gmail.com",
    "displayName" : "Oom Frans",
    "accNumber" : "1234556",
    "accType" : "SVGS",
    "accName" : "Frans Mazhar",
    "scndIdTp" : "01",
    "scndIdVal" : "44443333",
    "cstmrTp" : "01",
    "cstmrId" : "220000022"
}