# Proxy Register  from channel
POST http://localhost:9002/komi-outbound/service HTTP/1.1
Content-Type: application/json
clientId: IB1

{
    "ProxyResolutionRequest": {
        "NoRef": "555552",
        "AccountNumber" : "01",
        "ProxyType" : "01",
        "ProxyValue" : "frans.mazhar@gmail.com"
    }
}
