# Proxy Resolution  from channel
POST http://localhost:9002/komi-outbound/service HTTP/1.1
Content-Type: application/json
Authorization: Basic CMS:password

{
    "ProxyResolutionRequest": {
        "NoRef": "11114",
        "SenderAccountNumber" : "22341111",
        "ProxyType" : "01",
        "ProxyValue" : "KTP-222044020"
    }
}
