# Proxy Register  from channel
POST http://localhost:9002/komi-outbound/service HTTP/1.1
Content-Type: application/json
clientId: CMS

{
    "ProxyRegistrationRequest": {
        "NoRef": "211002",
        "RegistrationType": "AMND",
        "ProxyType" : "02",
        "ProxyValue" : "frans.mazhar@gmail.com",
        "DisplayName" : "assshahaja",
        "AccountName" : "Fras Manse",
        "SecondaryIdType" : "01",
        "SecondaryIdValue" : "44443333",
        "CustomerType" : "01",
        "CustomerId" : "2200111022",
        "ResidentialStatus" : "01",
        "TownName" : "0300"
    }
}

