# Account Enquiry Request from channel
POST http://localhost:9002/services/channel/acctenquiry HTTP/1.1
Content-Type: application/json

{
  "AccountEnquiryRequest" : {
    "intrnRefId" : "Kdbl20004202-355",
    "channelType" : "01",
    "receivingParticipant" : "FASTIDJA",
    "amount" : 35000030,
    "categoryPurpose" : "03",
    "creditorAccountNumber" : "72080110031"
  }
}
