# Credit Transfer Request from channel
POST http://localhost:9002/services/channel/cstmrcrdtrn HTTP/1.1
Content-Type: application/json

{
  "CreditTransferRequest" : {
    "intrnRefId" : "adbl23llds004202-355",
    "channel" : "01",
    "categoryPurpose" : "03",
    "amount" : 35000030,
    "dbtrId" : "KTP-2004-323",
    "dbtrIdType" : "01",    // 01: PRIVATE
    "dbtrAccountNo" : "00933494",
    "dbtrAccountType" : "CACC",
    "recptBank" : "FASTIDJA",
    "crdtId" : "SIM-AAAA0403",
    "crdtIdType" : "02",   // 02: ORGANIZATION
    "crdtAccountNo" : "90003488399",
    "crdtAccountType" : "SVGS",
    "paymentInfo" : "Payment Description or notes, up to 140 characters in the line"
  }
}
