POST http://localhost:8080/services/api/pacs008 HTTP/1.1
Content-Type: application/json

{
  "pacs008Seed" : {
    "busMessageId" : "20210613INDOIDJA510O0500000001",
    "messageId" : "20210613INDOIDJA51000000002",
    "channelType" : "05",
    "categoryPurpose" : "01",
    "transactionType" : "510",
    "amount" : 5000400,
    "debtorName" : "JAMES BROWN",
    "debtorId" : "KTP-2004-323",
    "debtorIdType" : "Organization",
    "debtorAccountNumber" : "22220-3-44",
    "debtorAccountType" : "CACC",
    "receivingParticipant" : "CENAIDJA",
    "creditorName" : "JOHN SMITH",
    "creditorId" : "SIM-AAAA0403",
    "creditorIdType" : "Private",
    "creditorAccountNumber" : "04421994",
    "creditorAccountType" : "SVGS",
    "creditorAccountProxyIdType" : "02",
    "creditorAccountProxyId" : "john.smith@example.com",
    "paymentInfo" : "Payment Description or notes, up to 140 characters in the line"
  }
}

###
POST http://localhost:8080/services/case/ctreq HTTP/1.1
Content-Type: application/json

{
  "CreditTransferRequestInput" : {
    "messageId" : "adbl23llds004202-355",
    "channelType" : "01",
    "categoryPurpose" : "03",
    "amount" : 35000030,
    "debtorId" : "KTP-2004-323",
    "debtorIdType" : "Organization",
    "debtorAccountNumber" : "00933494",
    "debtorAccountType" : "CACC",
    "receivingParticipant" : "FASTIDJA",
    "creditorId" : "SIM-AAAA0403",
    "creditorIdType" : "Private",
    "creditorAccountNumber" : "90003488399",
    "creditorAccountType" : "SVGS",
    "paymentInfo" : "Payment Description or notes, up to 140 characters in the line"
  }
}


###

# Mock.io

POST http://demo3216691.mockable.io/acctenq1 HTTP/1.1
Content-Type: application/json

{"kirim" : "iya"}