# Account Enquiry Request from channel on generic endpoint
# Account Number 77xxxx TIMEOUT
POST http://localhost:9002/komi-outbound/service HTTP/1.1
Content-Type: application/json

{
  "AccountEnquiryRequest" : {
    "channelRefId" : "47169",
    "channel" : "Internet Banking",
    "recptBank" : "014",
    "amount" : 137400,
    "categoryPurpose" : "Purchase",
    "creditorAccountNumber" : "677589"
  }
}

###

POST http://localhost:9002/komi-outbound/routing HTTP/1.1
Content-Type: application/json

{
  "AccountEnquiryRequest" : {
    "channelRefId" : "41468",
    "channel" : "01",
    "recptBank" : "BMRIIDJA",
    "amount" : 1545500,
    "categoryPurpose" : "01",
    "creditorAccountNumber" : "1814449"
  }
}