# Account Enquiry Request from channel on generic endpoint
# Account Number 8xxxx TIMEOUT
POST http://localhost:9002/komi-outbound/service HTTP/1.1
Content-Type: application/json

{
  "AccountEnquiryRequest" : {
    "channelRefId" : "45168",
    "channel" : "Internet Banking",
    "recptBank" : "014",
    "amount" : 54500,
    "categoryPurpose" : "Purchase",
    "creditorAccountNumber" : "1819199"
  }
}

###

POST http://localhost:9002/komi-outbound/routing HTTP/1.1
Content-Type: application/json

{
  "AccountEnquiryRequest" : {
    "channelRefId" : "45168",
    "channel" : "01",
    "recptBank" : "BMRIIDJA",
    "amount" : 54500,
    "categoryPurpose" : "01",
    "creditorAccountNumber" : "1819199"
  }
}