# Credit Transfer Request from channel untuk personal
POST http://localhost:9002/services/channel/cstmrcrdtrn HTTP/1.1
Content-Type: application/json

{
  "CreditTransferRequest" : {
    "intrnRefId" : "236.2473-34",
    "channel" : "01",
    "categoryPurpose" : "01",
    "amount" : 204400,
    "dbtrIdType" : "01",    
    "dbtrId"  : "KTP-2004050",
    "dbtrAccountNo" : "1434374",
    "dbtrAccountType" : "CACC",
    "recptBank" : "FASTIDJA",
    "crdtIdType" : "02",
    "crdtId" : "PT-A403",
    "crdtAccountNo" : "93722269",
    "crdtAccountType" : "SVGS",
    "paymentInfo" : "Untuk belikungin sayang"
  }
}

###

# Credit Transfer Request from channel untuk Organization
POST http://localhost:9002/services/channel/cstmrcrdtrn HTTP/1.1

{
  "CreditTransferRequest" : {
    "intrnRefId" : "KA.4004202-355",
    "channel" : "02",
    "categoryPurpose" : "01",
    "amount" : 350000300,

    "dbtrIdType" : "02",    
    "dbtrName": "PT Semaraing",
    "dbtrId" : "PTSMG",
    "dbtrAccountNo" : "9100004374",
    "dbtrAccountType" : "CACC",

    "recptBank" : "FASTIDJA",

    "crdtIdType" : "02",   
    "crdtName": "PT Semaraing",
    "crdtId" : "CV-A403",
    "crdtAccountNo" : "934008199",
    "crdtAccountType" : "SVGS",
    "paymentInfo" : "Untuk beli makan sayang"
  }
}
