# Proxy Register  from channel
POST http://localhost:9002/komi-outbound/service HTTP/1.1
Content-Type: application/json

{
    "ProxyRegistrationRequest": {
        "intrnRefId": "5540",
        "channel" : "Internet Banking",
        "registrationType" : "NEWR",
        "proxyType" : "02",
        "proxyValue" : "frans.mazhar@gmail.com",
        "registerDisplayName" : "Andi aja",
        "registerAccountNumber" : "14556",
        "registerAccountType" : "SVGS",
        "registerAccountName" : "Fras Manse",
        "registerSecondIdType" : "01",
        "registerSecondIdValue" : "44443333",
        "customerType" : "01",
        "customerId" : "220000022",
        "residentialStatus" : "01",
        "townName" : "0300"
    }
}

###

POST http://localhost:9002/komi-outbound/service HTTP/1.1
Content-Type: application/json

{
    "ProxyRegistrationRequest": {
        "intrnRefId": "5540",
        "channel" : "Internet Banking",
        "registrationType" : "PORT",
        "proxyType" : "02",
        "proxyValue" : "frans.mazhar@gmail.com",
        "registerAgentId" : "BMRIIDJA",
        "registerDisplayName" : "Andi aja",
        "registerAccountNumber" : "14556",
        "registerAccountType" : "SVGS",
        "registerAccountName" : "Fras Manse",
        "registerSecondIdType" : "01",
        "registerSecondIdValue" : "44443333",
        "customerType" : "01",
        "customerId" : "220000022",
        "residentialStatus" : "01",
        "townName" : "0300"
    }
}
