# CREDIT TRANSFER SETTLEMENT CONFIRMATION 
POST http://localhost:9001/services/api/inbound HTTP/1.1
Content-Type: application/json

{
	"BusMsg": {
		"AppHdr": {
			"Fr": {
				"FIId": {
					"FinInstnId": {
						"Othr": {
							"Id": "INDOIDJA"
						}
					}
				}
			},
			"To": {
				"FIId": {
					"FinInstnId": {
						"Othr": {
							"Id": "FASTIDJA"
						}
					}
				}
			},
			"BizMsgIdr": "20210618FASTIDJA010HRB12229018",
			"MsgDefIdr": "pacs.002.001.10",
			"BizSvc": "SETTLEMENTCONFIRMATION",
			"CreDt": "2021-03-01T20:00:00"
		},
		"Document": {
			"FIToFIPmtStsRpt": {
				"GrpHdr": {
					"MsgId": "20210301FASTIDJA01012345678",
					"CreDtTm": "2021-03-01T19:00:00"
				},
				"OrgnlGrpInfAndSts": [
					{
						"OrgnlMsgId": "20210301INDOIDJA01012345678",
						"OrgnlMsgNmId": "pacs.008.001.08",
						"OrgnlCreDtTm": "2021-03-01T19:00:00"
					}
				],
				"TxInfAndSts": [
					{
						"OrgnlEndToEndId": "20210301INDOIDJA010ORB12345678",
						"OrgnlTxId": "20210301INDOIDJA01012345678",
						"TxSts": "ACTC",
						"StsRsnInf": [
							{
								"Rsn": {
									"Prtry": "U000"
								},
								"AddtlInf": [
									"O 1234"
								]
							}
						],
						"OrgnlTxRef": {
							"IntrBkSttlmDt": "2021-03-01T00:00:00",
							"Dbtr": {
								"Pty": {
									"Nm": "JAMES BROWN"
								}
							},
							"DbtrAcct": {
								"Id": {
									"Othr": {
										"Id": "123456789"
									}
								},
								"Tp": {
									"Prtry": "CACC"
								}
							},
							"DbtrAgt": {
								"FinInstnId": {
									"Othr": {
										"Id": "INDOIDJA"
									}
								}
							},
							"CdtrAgt": {
								"FinInstnId": {
									"Othr": {
										"Id": "CENAIDJA"
									}
								}
							},
							"Cdtr": {
								"Pty": {
									"Nm": "JOHN SMITH"
								}
							},
							"CdtrAcct": {
								"Id": {
									"Othr": {
										"Id": "987654321"
									}
								},
								"Tp": {
									"Prtry": "SVGS"
								}
							}
						},
						"SplmtryData": [
							{
								"Envlp": {
									"Dbtr": {
										"Tp": "01",
										"Id": "0102030405060708",
										"RsdntSts": "01",
										"TwnNm": "0300"
									},
									"Cdtr": {
										"Tp": "01",
										"Id": "0807060504030201",
										"RsdntSts": "01",
										"TwnNm": "0300"
									},
									"DbtrAgtAcct": {
										"Id": {
											"Othr": {
												"Id": "654321098"
											}
										}
									},
									"CdtrAgtAcct": {
										"Id": {
											"Othr": {
												"Id": "890123456"
											}
										}
									}
								}
							}
						]
					}
				]
			}
		}
	}
}

###

# ACCOUNT ENQUIRY REQUEST INBOUND
POST http://localhost:9001/services/api/inbound HTTP/1.1
Content-Type: application/json

{
  "BusMsg" : {
    "AppHdr" : {
      "Fr" : {
        "FIId" : {
          "FinInstnId" : {
            "Othr" : {
              "Id" : "FASTIDJA"
            }
          }
        }
      },
      "To" : {
        "FIId" : {
          "FinInstnId" : {
            "Othr" : {
              "Id" : "INDOIDJA"
            }
          }
        }
      },
      "BizMsgIdr" : "20210627FASTIDJA010O5104104450",
      "MsgDefIdr" : "pacs.008.001.08",
      "CreDt" : "2021-06-26T20:06:59"
    },
    "Document" : {
      "FIToFICstmrCdtTrf" : {
        "GrpHdr" : {
          "MsgId" : "20210626FASTIDJA01004124663",
          "CreDtTm" : "2021-06-26T20:06:59.820",
          "NbOfTxs" : "1",
          "SttlmInf" : {
            "SttlmMtd" : "CLRG"
          }
        },
        "CdtTrfTxInf" : [ {
          "PmtId" : {
            "EndToEndId" : "20210616FASTIDJA010O0100004001",
            "TxId" : "20210616FASTIDJA01000004002"
          },
          "IntrBkSttlmAmt" : {
            "Value" : "20000000.20",
            "Ccy" : "IDR"
          },
          "ChrgBr" : "DEBT",
          "Dbtr" : { },
          "DbtrAgt" : {
            "FinInstnId" : {
              "Othr" : {
                "Id" : "FASTIDJA"
              }
            }
          },
          "CdtrAgt" : {
            "FinInstnId" : {
              "Othr" : {
                "Id" : "INDOIDJA"
              }
            }
          },
          "Cdtr" : { },
          "CdtrAcct" : {
            "Id" : {
              "Othr" : {
                "Id" : "500030312244"
              }
            }
          }
        } ]
      }
    }
  }
}

###

