insert into status_reason (status_reason_code,description,status_code) values ('U000','Success/ Transaction Accepted','ACSP');
insert into status_reason (status_reason_code,description,status_code) values ('U002','Success/ Transaction Accepted Stored in SAF','ACTC');
insert into status_reason (status_reason_code,description,status_code) values ('U101','Tenant Not Found','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U102','Tenant Not Active','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U103','Tenant Undefined','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U104','Inbound Scheme Not Found','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U106','Original Payment Not Found','OTHR');
insert into status_reason (status_reason_code,description,status_code) values ('U107','Original Payment Rejected','OTHR');
insert into status_reason (status_reason_code,description,status_code) values ('U108','Original Payment Not Responded','OTHR');
insert into status_reason (status_reason_code,description,status_code) values ('U110',' Payment Not Accepted','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U111','Minimum Amount Check Failed','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U112','Maximum Amount Check Failed','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U114','Mod 10 check failed','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U115','Date Sent Tolerance Check failed','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U116','Date Settlement Tolerance Check failed','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U117','Original Date Tolerance configuration error','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U118','Original Date Tolerance check failed','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U119','Session Validation Failed','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U121','Inbound Bank Not Found','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U122','Inbound Bank Not Active','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U123','Product Undefined','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U124','Bank Code Not Found','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U125','Inbound Bank Id Cannot be Determined (Bank Classifier not found)','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U126','Outbound Bank Cannot be Determined','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U128','Outbound Bank Not Active','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U129','Payee Bank Unavailable','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U130','Inbound Settlement Bank not found','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U131','Outbound Settlement Bank not found','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U132','Inbound Settlement Bank Inactive','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U134','Outbound Settlement Bank Inactive','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U135','Pre-Authorization Match Not Found','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U136','Pre-Authorization Bank Account Check Failed','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U137','Pre-Authorization Timeout','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U138','Pre-Authorization Config Not Found','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U139','Pre-Authorization Endpoint or Channel Not Configured','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U140','Pre-Authorization Exception No Response Returned','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U141','Pre-Authorization Exception','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U142','Pre-Authorization Stand-In Limit Exceeded','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U143','Pre-Authorization Stand-In Account Not Found','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U144','Pre-Authorization Stand-In Account Inactive','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U145','Pre-Authorization Stand-In Insufficient Funds','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U146','Pre-Authorization Stand-In Not Permitted','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U147','Pre-Authorization No Stand-In Response','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U149','Duplicate Transaction','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U150','Notification Configuration Not Found','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U151','Notification Endpoint Or Channel Not Configured','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U155','Fraud Check Failed','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U156','Sanction Check Failed','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U157','AML Check Failed','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U159','Pre-Authorization Stand-In Rejected with Default Status','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U160','Settlement Rules Not Found','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U161','Settlement Endpoint Or Channel Not Configured','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U162','Settlement Confirmation Not Received','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U163','Forwarded Settlement Confirmation Response Not Received','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U164','Settlement Total Management Not Configured','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U170','Online Route Not Found','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U171','Online Authorization Exception','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U172','Online Authorization Exception No Response returned','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U173','Online Authorization Exception Timeout','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U180','Authorization Service is Not Configured','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U181','Stand-In Limit Exceeded','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U182','Stand In Account Not Found','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U183','Stand In Account Inactive','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U184','Stand In Insufficient Funds','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U185','Stand In Not Permitted','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U186','Stand In No Response','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U187','Stand In forwarding Advice cannot be delivered','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U189','Stand-In Rejected With Default Status','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U191','Liquidity Rules Not Found','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U192','Liquidity Position Validation Rule not found (Threshold limits)','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U193','Liquidity Position Validation Failure','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U194','Insufficient Liquidity to process payment','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U195','Liquidity Forced Payment Rejection','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U196','Liquidity Parameter Invalid Or Null','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U197','Liquidity Parameters Not Found','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U198','Liquidity Validation Not Found','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U199','Liquidity Position Definition Not Found','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U200','LQM Maximum Amount Not Found','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U201','LQM Maximum Amount Exceeded','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U202','LQM Net Sender Threshold Limit Not Found','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U203','LQM Insufficient Net Sender Funds','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U205','Scheme Settlement Body Unavailable','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U206','Settlement Rejection','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U207','Default Settlement Body Not Defined','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U208','Settlement Forward Confirmation Send Failed','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U209','Settlement Forward Confirmation Receive Failed','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U210','Outbound Scheme Not Found','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U211','Outbound Scheme Not Active','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U212','Connector Not Found','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U213','Connector Configuration Error','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U214','Clearing Rejection','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U215','Message Rejected with Admi.002','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U220','Exception Handler Failure','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U799','Alias Management Rule not found','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U801','Addressing Agency cannot be determined','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U802','Addressing Privilege not defined','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U803','Insufficient Privilege','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U804','Alias Not Found Or Inactive','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U805','Alias Is Suspended / Activated','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U806','Alias belongs to same FI but different account','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U807','Alias already registered with another FI','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U808','Alias already registered with the same account','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U809','Not sufficient privilege to perform addressing action on an alias','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U810','Alias Request Failed','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U811','Alias suspended by Administrator','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U812','Alias Destination Not Configured','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U813','Cache Alias Maintenance Failed','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U814','Alias already registered with same FI','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U815','Duplicate Alias Service Request','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U900','Internal Timeout','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U901','System Malfunction','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U902','Connection Or Communication Error','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U904','Endpoint Error','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U990','Session Error','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U992','Response Not Delivered','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U993','Reason Code not determined in response ','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U999','Signature Verification Failure','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U221','MandateRulesNotFound','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U222','MandateMasterUpdateError','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U223','MandateRecordNotFound','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U224','MandateStartDateLessThanCurrentDate','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U225','MandateStartDateFormatError','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U226','MandateEndDateLessThanCurrentDate','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U227','MandateEndDateFormatError','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U228','MandateFrequencyTypeValidationError','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U229','MandateUpdaterNotKnown','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U230','MandateSenderNotAllowedToUpdate','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U231','MandateStatusValidationError','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U232','AmountGreaterThanMaximumLimit','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U233','MadateAmountMissing','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U234','RequestBeforeMandateStartDate','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U235','FutureMandateCannotBeUpdated','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U236','ExpiredMandateCannotBeUpdated','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U237','CancelledMandateCannotBeUpdated','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U238','RequestAfterMandateEndDate','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U239','HoldDateExceedsExipryDate','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U851','General Purpose Rules Not Found','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U312','RequestForPayNotFound','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U313','RequestForPayAlreadyProcessed','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U314','RequestForPayAlreadyRejected','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U315','RequestForPayInvalidState','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U316','RequestForPayAlreadyReceived','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U317','RequestForPayInvalidDbtrAgt','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U318','ExpiryDateLessThanCurrentDate','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U319','ExpiryDateFormatError','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U320','RequestedExecutionDateLessThanCurrentDate','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U321','RequestedExecutionDateFormatError','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U310','RequestForPayExpired','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U311','RequestForPayAlreadyTransferred','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U322','MandateIsNotActive','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U323','InvalidDebtorAgent','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U324','InvalidOriginalDebtorAgent','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U325','MandateAlreadyTransferred','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U300-U309','Reserved for private use ','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U326','RequestForPayAlreadyAccepted','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U327','MerchantNotActive','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U328','MerchantProductNotFound','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U329','MerchantNotFound','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U330','MerchantParameterNotFound','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U331','MerchantMinAmountCheckFailed','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U332','MerchantMaxAmountCheckFailed','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U333','DateXpryCheckFailed','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U334','MandateIsNotPending','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U335','RPFLookupRulesNotFound','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U336','PreAuthExpiryDateFormatError','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U337','PreAuthExpiryDateExceedsMandateExipryDate','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U338','PreAuthExpiryDateLessThanCreDtTm','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U339','PreAuthExpiryDateLessThanCurrentDate','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U340','MechantProductNotActive','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U341','MerchantValidationRuleNotFound','RJCT');
insert into status_reason (status_reason_code,description,status_code) values ('U342','MerchantProductBankCodeNotFound','RJCT');