# ACCOUNT ENQUIRY FROM CI-HUB
POST http://localhost:9001/services/api/inbound HTTP/1.1
Content-Type: application/json

{
  "BusMsg" : {
    "AppHdr" : {
      "Fr" : {
        "Fiid" : {
          "FinInstnId" : {
            "Othr" : {
              "Id" : "FASTIDJA"
            }
          }
        }
      },
      "To" : {
        "Fiid" : {
          "FinInstnId" : {
            "Othr" : {
              "Id" : "MNDRIDJA"
            }
          }
        }
      },
      "BizMsgIdr" : "20210914FASTIDJA510ORB00000001",
      "MsgDefIdr" : "pacs.008.001.08",
      "CreDt" : "2021-09-12T09:00:00"
    },
    "Document" : {
      "FitoFICstmrCdtTrf" : {
        "GrpHdr" : {
          "MsgId" : "20210912FASTIDJA51000000002",
          "CreDtTm" : "2021-03-01T19:00:00",
          "NbOfTxs" : "1",
          "SttlmInf" : {
            "SttlmMtd" : "CLRG"
          }
        },
        "CdtTrfTxInf" : [ {
          "PmtId" : {
            "EndToEndId" : "20210914FASTIDJA510ORB00000001",
            "TxId" : "20210912FASTIDJA51000000002"
          },
          "IntrBkSttlmAmt" : {
            "Value" : "51234.56",
            "Ccy" : "IDR"
          },
          "ChrgBr" : "DEBT",
          "Dbtr" : { },
          "DbtrAgt" : {
            "FinInstnId" : {
              "Othr" : {
                "Id" : "FASTIDJA"
              }
            }
          },
          "CdtrAgt" : {
            "FinInstnId" : {
              "Othr" : {
                "Id" : "MNDRIDJA"
              }
            }
          },
          "Cdtr" : { },
          "CdtrAcct" : {
            "Id" : {
              "Othr" : {
                "Id" : "98774321"
              }
            }
          }
        } ]
      }
    }
  }
}