POST http://localhost:9001/komi-inbound/json/service HTTP/1.1
Content-Type: application/json

{
  "BusMsg": {
    "AppHdr": {
      "Fr": {
        "FIId": {
          "FinInstnId": {
            "Othr": {
              "Id": "CENAIDJA"
            }
          }
        }
      },
      "To": {
        "FIId": {
          "FinInstnId": {
            "Othr": {
              "Id": "SIHBIDJ1"
            }
          }
        }
      },
      "BizMsgIdr": "20220111CENAIDJA011R0200000983",
      "MsgDefIdr": "pacs.008.001.08",
      "CreDt": "2022-01-11T11:15:20Z"
    },
    "Document": {
      "FIToFICstmrCdtTrf": {
        "GrpHdr": {
          "MsgId": "20220111CENAIDJA01100000641",
          "CreDtTm": "2022-01-11T18:15:20.925",
          "NbOfTxs": "1",
          "SttlmInf": {
            "SttlmMtd": "CLRG"
          }
        },
        "CdtTrfTxInf": [
          {
            "PmtId": {
              "EndToEndId": "20220111CENAIDJA011R0200000983",
              "TxId": "20220111SIHBIDJ101000000741"
            },
            "PmtTpInf": {
              "LclInstrm": {
                "Prtry": "02"
              },
              "CtgyPurp": {
                "Prtry": "01001"
              }
            },
            "IntrBkSttlmAmt": {
              "Value": "12000.57",
              "Ccy": "IDR"
            },
            "ChrgBr": "DEBT",
            "Dbtr": {
              "Nm": "Joko Susilo",
              "Id": {
                "PrvtId": {
                  "Othr": [
                    {
                      "Id": "KTP-205772715"
                    }
                  ]
                }
              }
            },
            "DbtrAcct": {
              "Id": {
                "Othr": {
                  "Id": "112211333"
                }
              },
              "Tp": {
                "Prtry": "CACC"
              },
              "Prxy": {
                "Tp": {}
              }
            },
            "DbtrAgt": {
              "FinInstnId": {
                "Othr": {
                  "Id": "SIHBIDJ1"
                }
              }
            },
            "CdtrAgt": {
              "FinInstnId": {
                "Othr": {
                  "Id": "SIHBIDJ1"
                }
              }
            },
            "Cdtr": {
              "Nm": "Joko Susilo",
              "Id": {
                "PrvtId": {
                  "Othr": [
                    {
                      "Id": "KTP-205772715"
                    }
                  ]
                }
              }
            },
            "CdtrAcct": {
              "Id": {
                "Othr": {
                  "Id": "112211333"
                }
              },
              "Tp": {
                "Prtry": "CACC"
              },
              "Prxy": {
                "Tp": {}
              }
            },
            "RmtInf": {
              "Ustrd": [
                "REVERSAL"
              ]
            },
            "SplmtryData": [
              {
                "Envlp": {
                  "Dtl": {
                    "Dbtr": {
                      "Tp": "01",
                      "RsdntSts": "01",
                      "TwnNm": "0300"
                    },
                    "Cdtr": {
                      "Tp": "01",
                      "RsdntSts": "01",
                      "TwnNm": "0300"
                    }
                  }
                }
              }
            ]
          }
        ]
      }
    }
  }
}