FROM postgres:12.7
# COPY cr_tables.sql /docker-entrypoint-initdb.d/
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_DB=komidb
EXPOSE 5432

# docker build -t fransmzh/komidb:1.0 .
# docker push fransmzh/komidb:1.0